stages:
  - job

variables:
  GITLAB_TOKEN: "glpat-XLN9V9t-kYxADyNKfKMg"

job1:
  stage: job
  tags: 
    - EmCare
  script:
    - git clone "https://oauth2:$GITLAB_TOKEN@argusgit.argusoft.com/who-public/emcare.git"