stages:
  - build
  - job1

build:
  stage: build
  tags:
    - EmCare
 
job1:
  script:
    - git clone https://gitlab-ci-token:glpat-XLN9V9t-kYxADyNKfKMg@https://argusgit.argusoft.com/who-public/emcare.git