export { LoginComponent } from './components/login/login.component';
export { SignupComponent } from './components/signup/signup.component';
// export { ManagePatientComponent } from './components/Patient/managePatient/patient.component';
// export { ShowPatientComponent } from './components/Patient/show-patient/show-patient.component';
// export { ManageOrganizationComponent } from './components/Organization/manage-organization/manage-organization.component';
// export { ShowOrganizationComponent } from './components/Organization/show-organization/show-organization.component';
export { LocationTypeComponent } from './components/Location/location-type/manage-location-type/location-type.component';
export { LocationManagementComponent } from './components/Location/location-management/manage-location/location-management.component';
export { ShowLocationComponent } from './components/Location/location-management/show-location/show-location.component';
export { ShowLocationTypeComponent } from './components/Location/location-type/show-location-type/show-location-type.component';
export { LocationService } from './services/location.service';
export { DeviceManagementComponent } from './components/Device-Management/device-management/device-management.component';
export { DeviceListComponent } from './components/Device-Management/device-list/device-list.component';
export { DeviceManagementService } from './services/device-management.service';
export { UserListComponent } from './components/User/user-list/user-list.component';
export { ManageUserComponent } from './components/User/manage-user/manage-user.component';
export { UserManagementService } from './services/user-management.service';