export { LoginComponent } from './components/login/login.component';
export { SignupComponent } from './components/signup/signup.component';
// export { ManagePatientComponent } from './components/Patient/managePatient/patient.component';
// export { ShowPatientComponent } from './components/Patient/show-patient/show-patient.component';
// export { ManageOrganizationComponent } from './components/Organization/manage-organization/manage-organization.component';
// export { ShowOrganizationComponent } from './components/Organization/show-organization/show-organization.component';
export { LocationTypeComponent } from './components/Location/location-type/manage-location-type/location-type.component';
export { LocationManagementComponent } from './components/Location/location-management/manage-location/location-management.component';
export { ShowLocationComponent } from './components/Location/location-management/show-location/show-location.component';
export { ShowLocationTypeComponent } from './components/Location/location-type/show-location-type/show-location-type.component';
export { LocationService } from './services/location.service';
export { DeviceManagementComponent } from './components/Device-Management/device-management/device-management.component';
export { DeviceListComponent } from './components/Device-Management/device-list/device-list.component';
export { DeviceManagementService } from './services/device-management.service';
export { UserListComponent } from './components/User/user-list/user-list.component';
export { ManageUserComponent } from './components/User/manage-user/manage-user.component';
export { ConfirmUserComponent } from './components/User/confirm-user/confirm-user.component';
export { UserManagementService } from './services/user-management.service';
export { LocationFilterComponent } from './components/Location/location-filter/location-filter.component';
export { FeatureListComponent } from './components/Feature/feature-list/feature-list.component';
export { ManageFeatureComponent } from './components/Feature/manage-feature/manage-feature.component';
export { FeatureManagementService } from './services/feature-management.service';
export { ManageTranslationsComponent } from './components/manage-translations/manage-translations.component';
export { ComparePatientComponent } from './components/patient-management/compare-patient/compare-patient.component';
export { ManageFacilityComponent } from './components/Facility/manage-facility/manage-facility.component';
export { PatientListComponent } from './components/patient-management/patient-list/patient-list.component';
export { ManageRoleComponent } from './components/role-management/manage-role/manage-role.component';
export { ShowRoleComponent } from './components/role-management/show-role/show-role.component';
export { ManageProfileComponent } from './components/manage-profile/manage-profile.component';
export { QuestionnaireBuilderComponent } from './components/questionnaire-management/questionnaire-builder/questionnaire-builder.component';
export { QuestionnaireListComponent } from './components/questionnaire-management/questionnaire-list/questionnaire-list.component';
export { ShowFacilityComponent } from './components/Facility/show-facility/show-facility.component';
export { LocationDropdownComponent } from './components/Location/location-filter/location-dropdown/location-dropdown.component';
export { LanguageListComponent } from './components/language-list/language-list.component';
export { ForgotPasswordComponent } from './components/forgot-password/forgot-password.component';
export { AdminPanelComponent } from './components/admin-panel/admin-panel.component';
